name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test
        
  build-and-push:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK and Docker
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Docker
        uses: docker/setup-docker@v2
          
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cloud.cbh.kth.se
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build with Maven and Docker
        run: |
          npm run build
          docker build -t ${{ secrets.DOCKER_TAG }} .

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_TAG }}  
